### ISSUE TITLE
64 bit risc v core from tilelink/socSim.scala.

### ISSUE THREAD

**Issue by HimalSubedi787** [SpinalHDL/NaxRiscv#68]
Dear charles,

I want to have 64 bit risc v core in tilelink/socSim.scala.  i modify **/platform/TilelinkNaxRiscvFiber.scala**  and it can compile the code but when i run 64 bit elf file in  **runMain naxriscv.platform.tilelinkdemo.SocSim** it shows some strange errors 

moreover, I am also wondering How can I add ScopeFiber() from tilelink/socSim.scala to Litex/NaxSoc.scala?

```
sbt

compile

sbt:NaxRiscv> runMain naxriscv.platform.tilelinkdemo.SocSim --load-elf ext/NaxSoftware/baremetal/socdemo/build/rv64ima/socdemo.elf --trace --nax-count 2 --no-rvls
```

**by making following changes** 

https://github.com/SpinalHDL/NaxRiscv/blob/throttle_l2/src/main/scala/naxriscv/platform/tilelinkdemo/SocDemo.scala#L19 
https://github.com/SpinalHDL/NaxRiscv/blob/throttle_l2/src/main/scala/naxriscv/platform/tilelinkdemo/SocSim.scala#L84 
```
line 19 of Socdemo.scala 

class SocDemo(cpuCount : Int, withL2 : Boolean = true, xlen : Int = 64, asic : Boolean = false) extends Component {


SocSim.Scala line 84

class SocDemoSim(cpuCount : Int) extends SocDemo(cpuCount, withL2 = withL2, xlen = 64, asic = asic){


gedit src/main/scala/naxriscv/platform/TilelinkNaxRiscvFiber.scala 


  def setCoherentConfig(hartId : Int, asic : Boolean = false) : this.type = {
    plugins load Config.plugins(
      withCoherency = true,
  +    xlen = 64,
      withRdTime = false,
      aluCount = 2,
      decodeCount = 2,
      ioRange = a => a(31 downto 28) === 0x1,
      hartId = hartId,
      asic = asic
    )
 ```   
    
    It throws strange errors. 
    
    
```
    [info] [Progress] Simulation workspace in /home/hsubedi/instruction_test_bed/riscv_NAX_2_l2_cache_new_pull/NaxRiscv5_gtkwave_5_Nov/NaxRiscv/./simWorkspace/SocDemo
[info] [Progress] Verilator compilation started
[info] [Progress] Verilator compilation done in 22154.623 ms
[info] [Progress] Start SocDemo test simulation with seed 2
[info] [Error] Simulation failed at time=0
[error] Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 4096 out of bounds for length 4096
[error] 	at spinal.lib.sim.SparseMemory.getElseAlocate(Misc.scala:134)
[error] 	at spinal.lib.sim.SparseMemory.write(Misc.scala:163)
[error] 	at spinal.lib.misc.Elf$$anonfun$load$1.apply(Elf.scala:39)
[error] 	at spinal.lib.misc.Elf$$anonfun$load$1.apply(Elf.scala:35)
[error] 	at spinal.lib.misc.Elf$$anonfun$foreachSection$1.apply$mcVI$sp(Elf.scala:16)
[error] 	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
[error] 	at spinal.lib.misc.Elf.foreachSection(Elf.scala:14)
[error] 	at spinal.lib.misc.Elf.load(Elf.scala:35)
[error] 	at naxriscv.platform.tilelinkdemo.SocSim$$anonfun$testIt$5.apply(SocSim.scala:189)
[error] 	at naxriscv.platform.tilelinkdemo.SocSim$$anonfun$testIt$5.apply(SocSim.scala:187)
[error] 	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[error] 	at naxriscv.platform.tilelinkdemo.SocSim$.testIt(SocSim.scala:187)
[error] 	at naxriscv.platform.tilelinkdemo.SocSim$$anonfun$17.apply(SocSim.scala:136)
[error] 	at naxriscv.platform.tilelinkdemo.SocSim$$anonfun$17.apply(SocSim.scala:136)
[error] 	at spinal.core.sim.SimCompiled$$anonfun$doSimApi$1.apply$mcV$sp(SimBootstraps.scala:606)
[error] 	at spinal.sim.SimThread$$anonfun$1.apply$mcV$sp(SimThread.scala:93)
[error] 	at spinal.sim.JvmThread.run(SimManager.scala:51)
[error] Nonzero exit code returned from runner: 1
[error] (Compile / runMain) Nonzero exit code returned from runner: 1
[error] Total time: 30 s, completed Nov 9, 2023, 7:50:55 PM
   ```
   
Here we are running of socdemo by  **runMain naxriscv.platform.tilelinkdemo.SocSim** in sbt server. If i wish to run this particular socdemo, which has probe of L2 cache miss  in **Litex/FPGA**,  it will be interesting to see result.  
   
can you help me in tweeking of socdemo so it will be possible to run 64 bit risc v core and load 64 bit elf file ? 

Thank you

**Comment by Dolu1990** [comment]
Should be ok now, got it to work with 
--load-elf ext/NaxSoftware/baremetal/dhrystone/build/rv64ima/dhrystone.elf  --xlen 64

**Comment by Dolu1990** [comment]
> even this does not work
with 2 core

Dhrystone is only compiled to support 1 core. So it is normaly behaviour it crashes

> [info] Sim starting <3
[info] GET param=0 source=0 addr=0x0 bytes=4
[info] [Error] Simulation failed at time=7270

The CPU do an access at address 0.
What is your .asm from your software ?

**Comment by Dolu1990** [comment]
SocSim isn't intented to be use in FPGA.
Instead you could use the litex integration, which relay on NaxSoc.
