### ISSUE TITLE
Loop when change GShare RAM

### ISSUE THREAD

**Issue by zyn810039594** [SpinalHDL/NaxRiscv#73]
Hello!

By default, gshare have a 4096×8 ram for gshare counter. However, the shape of the 4096×8 ram is too long to run at a high period. So I want to change the 4096×8 ram to a 512×64 ram. My solution is to write data by 8-bits mask, and read data by judging the last 3-bits addresses. But spinal calls loop...
I've only changed the `GSharePlugin.scala` ,and where I changed has been commented as:
```scala
// ----------------------------------------------------------------
// Where I changed
// ----------------------------------------------------------------
```
Here's the code I changed:
```scala
class GSharePlugin(var historyWidth : Int,
                   var entries : Int = 0,
                   var memBytes : BigInt = null,
                   var readAt : Int = 0,
                   var counterWidth : Int = 2,
                   var readAsync : Boolean = false) extends Plugin with FetchConditionalPrediction with HistoryUser{

  override def useHistoryAt = readAt
  override def historyWidthUsed = historyWidth
  override def getPredictionAt(stageId: Int) = getService[FetchPlugin].getStage(stageId)(setup.keys.GSHARE_COUNTER).map(_.msb)

  val setup = create early new Area{
    val fetch = getService[FetchPlugin]
    val frontend = getService[FrontendPlugin]
    val branchContext = getService[BranchContextPlugin]
    val aligner = getService[AlignerPlugin]

    fetch.retain()
    frontend.retain()
    branchContext.retain()


    val keys = new AreaRoot {
      val GSHARE_COUNTER = Stageable(Vec.fill(SLICE_COUNT)(UInt(counterWidth bits)))
    }

    aligner.addLastWordContext(
      keys.GSHARE_COUNTER
    )
    branchContext.dispatchWrite(
      keys.GSHARE_COUNTER
    )
  }

  val logic = create late new Area{
    val fetch = getService[FetchPlugin]
    val branchContext = getService[BranchContextPlugin]
    val predictor = getService[DecoderPredictionPlugin]
    val frontend = getService[FrontendPlugin]
    val BRANCH_HISTORY = getService[HistoryPlugin].keys.BRANCH_HISTORY

    var words = entries/SLICE_COUNT
    if(memBytes != null) words = (1 <<(log2Up(memBytes.toInt*8/counterWidth+1)-1)) / SLICE_COUNT
    assert(words != 0)
    assert(isPow2(words))

    val keys = setup.keys

    def hashWidth = log2Up(words)
    def gshareHash(address : UInt, history : Bits) = address(SLICE_RANGE.high + 1, hashWidth bits).reversed ^ U(history).resized

    val mem = new Area{ //TODO bypass read durring write ?
      // ----------------------------------------------------------------
      // Where I changed
      // ----------------------------------------------------------------
      val counter = Mem.fill(words/8)(Vec(keys.GSHARE_COUNTER,8))
      val write = counter.writePortWithMask(8)
      if(GenerationFlags.simulation){
        counter.initBigInt(List.fill(counter.wordCount)(BigInt(0)))
      }
    }

    val BYPASS = Stageable(cloneOf(mem.write))
    val HASH = Stageable(UInt(hashWidth bits))

    val readCmd = new Area{
      val stage = fetch.getStage(readAt)
      import stage._

      HASH := gshareHash(FETCH_PC, BRANCH_HISTORY)
      stage(BYPASS) := mem.write
    }

    val readRsp = new Area{
      val stage = fetch.getStage(readAt+1)
      import stage._
      // ----------------------------------------------------------------
      // Where I changed
      // ----------------------------------------------------------------
      def readMem[T <: Data](mem : Mem[Vec[T]], address : UInt = readCmd.stage(HASH)) = {
        val addrReal = address(address.getWidth - 1 downto 3)
        val addrChoose = address(2 downto 0)
        readAsync match {
          case false => mem.readSync(addrReal, readCmd.stage.isReady)(addrChoose)
          case true  => mem.readAsync(addrReal)(addrChoose)
        }
      }
      stage(keys.GSHARE_COUNTER) := readMem(mem.counter)
      when(BYPASS.valid && stage(BYPASS).address === HASH){
        // ----------------------------------------------------------------
        // Where I changed
        // ----------------------------------------------------------------
        stage(keys.GSHARE_COUNTER) := stage(BYPASS).data(OHToUInt(stage(BYPASS).mask))
      }

      KeepAttribute(stage(keys.GSHARE_COUNTER))
    }

    val onDecompressed = new Area{
      val stage = frontend.pipeline.decompressed

      for(slotId <- 0 until Frontend.DECODE_COUNT) {
        stage(CONDITIONAL_TAKE_IT, slotId) := stage(keys.GSHARE_COUNTER, slotId).map(_.msb).asBits
      }
    }

    val onLearn = new Area{
      val ctx = branchContext.learnRead(branchContext.keys.BRANCH_FINAL)
      val hash = gshareHash(ctx.pcOnLastSlice, branchContext.learnRead(BRANCH_HISTORY))

      val counters = branchContext.learnRead(keys.GSHARE_COUNTER)
      val updated = keys.GSHARE_COUNTER()
      val incrValue = ctx.taken ? U(1) | U((1 << counterWidth)-1)
      val overflow = False
      for(sliceId <- 0 until SLICE_COUNT){
        updated(sliceId) := counters(sliceId) + incrValue.andMask(ctx.pcOnLastSlice(SLICE_RANGE) === sliceId)
        overflow setWhen(ctx.taken && counters(sliceId).msb && !updated(sliceId).msb || !ctx.taken && !counters(sliceId).msb && updated(sliceId).msb)
      }
      // ----------------------------------------------------------------
      // Where I changed
      // ----------------------------------------------------------------
      mem.write.valid := branchContext.learnValid && branchContext.learnRead(IS_BRANCH) && !overflow
      mem.write.address := hash(hash.getWidth - 1 downto 3)
      mem.write.mask := UIntToOh(hash(2 downto 0))
      mem.write.data.clearAll()
      mem.write.data(hash(2 downto 0)) := updated
    }

    fetch.release()
    frontend.release()
    branchContext.release()
  }
}
```

And the error SpinalHDL printed is listed below:

```
Exception in thread "main" spinal.core.SpinalExit: 


 Error detected in phase PhaseCheckCombinationalLoops
********************************************************************************
********************************************************************************

COMBINATORIAL LOOP :
  Partial chain :
    >>> (toplevel/BtbPlugin_logic_applyIt_doIt :  Bool) at naxriscv.prediction.BtbPlugin$$anonfun$2$$anon$2$$anon$7.<init>(BtbPlugin.scala:110) >>>
    >>> (toplevel/BtbPlugin_setup_btbJump_valid :  Bool) at spinal.lib.Flow.<init>(Flow.scala:21) >>>
    >>> (toplevel/??? :  Bits[6 bits]) at spinal.lib.OHMasking$.firstV2(Utils.scala:210) >>>
    >>> (toplevel/??? :  Bool) at spinal.lib.OHMasking$.firstV2(Utils.scala:210) >>>
    >>> (toplevel/??? :  Bits[6 bits]) at spinal.lib.OHMasking$.firstV2(Utils.scala:212) >>>
    >>> (toplevel/PcPlugin_logic_jump_oh :  Bits[6 bits]) at jdk.internal.reflect.GeneratedConstructorAccessor12.newInstance(Unknown Source) >>>
    >>> (toplevel/PcPlugin_logic_jump_target :  UInt[32 bits]) at naxriscv.Global$$anonfun$6.apply(Parameters.scala:57) >>>
    >>> (toplevel/PcPlugin_logic_jump_target_1 :  UInt[32 bits]) at jdk.internal.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source) >>>
    >>> (toplevel/PcPlugin_logic_jump_pcLoad_payload_pc :  UInt[32 bits]) at naxriscv.interfaces.JumpCmd.<init>(Service.scala:35) >>>
    >>> (toplevel/PcPlugin_logic_fetchPc_pc :  UInt[32 bits]) at naxriscv.fetch.PcPlugin$$anonfun$5$$anon$2$$anon$5.<init>(PcPlugin.scala:83) >>>
    >>> (toplevel/PcPlugin_logic_fetchPc_output_payload :  UInt[32 bits]) at naxriscv.Global$$anonfun$6.apply(Parameters.scala:57) >>>
    >>> (toplevel/FetchPlugin_stages_0_Fetch_FETCH_PC :  UInt[32 bits]) at naxriscv.Global$$anonfun$6.apply(Parameters.scala:57) >>>
    >>> (toplevel/??? :  UInt[5 bits]) at naxriscv.prediction.GSharePlugin$$anonfun$5$$anon$3.gshareHash(GSharePlugin.scala:68) >>>
    >>> (toplevel/FetchPlugin_stages_0_GSharePlugin_logic_HASH :  UInt[5 bits]) at naxriscv.prediction.GSharePlugin$$anonfun$5$$anon$3$$anonfun$9.apply(GSharePlugin.scala:79) >>>
    >>> (toplevel/??? :  UInt[3 bits]) at naxriscv.prediction.GSharePlugin$$anonfun$5$$anon$3$$anon$6.readMem(GSharePlugin.scala:95) >>>
    >>> (toplevel/FetchPlugin_stages_1_GSHARE_COUNTER_0 :  UInt[2 bits]) at naxriscv.prediction.GSharePlugin$$anonfun$3$$anon$2$$anon$1$$anonfun$4$$anonfun$apply$1.apply(GSharePlugin.scala:42) >>>
    >>> (toplevel/BtbPlugin_logic_applyIt_prediction :  Bool) at jdk.internal.reflect.GeneratedConstructorAccessor13.newInstance(Unknown Source) >>>
    >>> (toplevel/BtbPlugin_logic_applyIt_needIt :  Bool) at naxriscv.prediction.BtbPlugin$$anonfun$2$$anon$2$$anon$7.<init>(BtbPlugin.scala:108) >>>

  Full chain :
    (toplevel/BtbPlugin_logic_applyIt_doIt :  Bool)
    (toplevel/BtbPlugin_setup_btbJump_valid :  Bool)
    Bits -> Bits
    Bits ## Bits
    (toplevel/??? :  Bits[6 bits])
    Bits(Int)
    (toplevel/??? :  Bool)
    Bool && Bool
    (toplevel/??? :  Bits[6 bits])
    (toplevel/PcPlugin_logic_jump_oh :  Bits[6 bits])
    Bits(Int)
    (Bool ? Bits | Bits)[32 bits]
    (Bits | Bits)[32 bits]
    (Bits | Bits)[32 bits]
    (Bits | Bits)[32 bits]
    (Bits -> UInt of 32 bits)
    (toplevel/PcPlugin_logic_jump_target :  UInt[32 bits])
    (toplevel/PcPlugin_logic_jump_target_1 :  UInt[32 bits])
    (toplevel/PcPlugin_logic_jump_pcLoad_payload_pc :  UInt[32 bits])
    (toplevel/PcPlugin_logic_fetchPc_pc :  UInt[32 bits])
    (toplevel/PcPlugin_logic_fetchPc_output_payload :  UInt[32 bits])
    (toplevel/FetchPlugin_stages_0_Fetch_FETCH_PC :  UInt[32 bits])
    UInt(Int downto Int)
    (toplevel/??? :  UInt[5 bits])
    UInt(Int)
    Bits -> Bits
    Bits ## Bits
    (Bits -> UInt of 5 bits)
    (UInt ^ UInt)[5 bits]
    (toplevel/FetchPlugin_stages_0_GSharePlugin_logic_HASH :  UInt[5 bits])
    UInt(Int downto Int)
    (toplevel/??? :  UInt[3 bits])
    mux of UInt[2 bits]
    (toplevel/FetchPlugin_stages_1_GSHARE_COUNTER_0 :  UInt[2 bits])
    UInt(Int)
    mux of Bool
    (toplevel/BtbPlugin_logic_applyIt_prediction :  Bool)
    ! Bool
    Bool && Bool
    ! Bool
    Bool && Bool
    (toplevel/BtbPlugin_logic_applyIt_needIt :  Bool)
    Bool && Bool
********************************************************************************
********************************************************************************

COMBINATORIAL LOOP :
  Partial chain :
    >>> (toplevel/BtbPlugin_logic_applyIt_prediction :  Bool) at jdk.internal.reflect.GeneratedConstructorAccessor13.newInstance(Unknown Source) >>>
    >>> (toplevel/BtbPlugin_setup_historyPush_taken :  Bits[1 bits]) at naxriscv.prediction.HistoryPush.<init>(HistoryPlugin.scala:24) >>>
    >>> (toplevel/HistoryPlugin_logic_update_pushes_0_stateNext_1 :  Bits[24 bits]) at jdk.internal.reflect.GeneratedConstructorAccessor12.newInstance(Unknown Source) >>>
    >>> (toplevel/HistoryPlugin_logic_onFetch_valueNext :  Bits[24 bits]) at jdk.internal.reflect.GeneratedConstructorAccessor12.newInstance(Unknown Source) >>>
    >>> (toplevel/FetchPlugin_stages_0_BRANCH_HISTORY :  Bits[24 bits]) at naxriscv.prediction.HistoryPlugin$$anonfun$4$$anon$1$$anonfun$5.apply(HistoryPlugin.scala:54) >>>
    >>> (toplevel/FetchPlugin_stages_0_GSharePlugin_logic_HASH :  UInt[5 bits]) at naxriscv.prediction.GSharePlugin$$anonfun$5$$anon$3$$anonfun$9.apply(GSharePlugin.scala:79) >>>
    >>> (toplevel/??? :  UInt[3 bits]) at naxriscv.prediction.GSharePlugin$$anonfun$5$$anon$3$$anon$6.readMem(GSharePlugin.scala:95) >>>
    >>> (toplevel/FetchPlugin_stages_1_GSHARE_COUNTER_0 :  UInt[2 bits]) at naxriscv.prediction.GSharePlugin$$anonfun$3$$anon$2$$anon$1$$anonfun$4$$anonfun$apply$1.apply(GSharePlugin.scala:42) >>>

  Full chain :
    (toplevel/BtbPlugin_logic_applyIt_prediction :  Bool)
    (toplevel/BtbPlugin_setup_historyPush_taken :  Bits[1 bits])
    Bits(Int)
    Bits -> Bits
    Bits ## Bits
    resize(Bits,24 bits)
    (toplevel/HistoryPlugin_logic_update_pushes_0_stateNext_1 :  Bits[24 bits])
    (toplevel/HistoryPlugin_logic_onFetch_valueNext :  Bits[24 bits])
    (toplevel/FetchPlugin_stages_0_BRANCH_HISTORY :  Bits[24 bits])
    (Bits -> UInt of 24 bits)
    resize(UInt,5 bits)
    (UInt ^ UInt)[5 bits]
    (toplevel/FetchPlugin_stages_0_GSharePlugin_logic_HASH :  UInt[5 bits])
    UInt(Int downto Int)
    (toplevel/??? :  UInt[3 bits])
    mux of UInt[2 bits]
    (toplevel/FetchPlugin_stages_1_GSHARE_COUNTER_0 :  UInt[2 bits])
    UInt(Int)
    mux of Bool
```

So, there're a few problem about that:

- Is this way not compatible for nax?
- If it's compatible, how should I fix the loop?
- If it's not compatible, is there any better idea to solve it?

That's all.Thanks for your help!

**Comment by Dolu1990** [comment]
Hi,

Here is the fix : 

```scala
      def readMem[T <: Data](mem : Mem[Vec[T]]) = {
        assert(!readAsync)
        val addrReal = readCmd.stage(HASH)(widthOf(HASH) - 1 downto 3)
        val addrChoose = this.stage(HASH)(2 downto 0)
        readAsync match {
          case false => mem.readSync(addrReal, readCmd.stage.isReady)(addrChoose)
          case true  => mem.readAsync(addrReal)(addrChoose)
        }
      }
```
The issue was that the code was using the address of stage 0 to mux the output of the readSync, so jumping stage -> creating combinatorial loop with history/pc updates

**Comment by zyn810039594** [comment]
Thanks for help! Problem resolved.
